network: 
  name: allcnn
  depth: orig
  reg:
    dropout: False
    weight_decay: !!null
  batch_norm: False
optimizer:
  name: SGD
  loss: categorical_crossentropy
  momentum: 0.9
  nesterov: True
train:
  lr:
    init_lr: 0.01 
    decay_factor: 0.1
    decay_epochs: [25, 40]
  batch_size:
    tr: 50
    val: 50
  epochs: 50
  simulate:
    bs_lr: bs # bs or lr
    rep_samples: !!null
    norep_samples: False
    true_epochs: False
data:
  data_file: ~/datasets/hdf5/mnist.hdf5
  group_tr: train
  group_val: test
  shuffle_train_val: False
  chunk_size: !!null
  queue_size: 50
daug:
  nodaug: nodaug.yml
  daug_params_file: nodaug.yml
  aug_per_img_tr: 1
  aug_per_img_val: 1
seeds:
  tf: 33
  np: 39
  daug: 59
  batch_shuffle: 47
  train_val: 27
metrics: [accuracy, top3]
