# Configuration according to: https://github.com/MadryLab/mnist_challenge/blob/master/config.json
network_name:                       'allcnn'
optimizer:                          'Adam'
loss:                               'categorical_crossentropy'
batch_size:                         100
max_steps:                          150
initial_lr:                         0.001 
lr_decay_factor:                    1.
decay_epochs:                       []
dropout:                            False
weight_decay:                       !!null
batch_norm:                         True
depth:                              'orig'
shuffle:                            False
